### ISSUE TITLE
Comparing only first byte?

### ISSUE THREAD

**Issue by eulores** [keithamus/rollup-plugin-brotli#11]
```js
    for (let i = 0; i < bytes.length; ++i) {
      matches = matches && bytes[0] === sourceBytes[0]
    }
```
The index should be changed from `0` to `i`
https://github.com/keithamus/rollup-plugin-brotli/blob/55ba63023d45219d3c11a820a557f76c6d17eefc/src/index.js#L18

**Comment by keithamus** [comment]
Oops! PRs welcome :smile:
