### ISSUE TITLE
Brotli and Gzip

### ISSUE THREAD

**Issue by EtienneBruines** [keithamus/rollup-plugin-brotli#4]
What would be the recommended configuration for using both the `gzip` as well as this` brotli` plugin?

I end up having `.js.gz.br` files :sweat_smile: 

```node
import gzip from 'rollup-plugin-gzip'
import brotli from "rollup-plugin-brotli";

export default {
    input: 'src/app.js',
    output: {
        dir: 'dist/',
        format: 'esm',
    },
    plugins: [
        gzip(),
        brotli(),
    ]
}
```

**Comment by keithamus** [comment]
Thanks for the issue report @EtienneBruines! I was able to reproduce and I've just pushed a fix out so that `2.0.2` will not output any `.br` files for already compressed assets. https://github.com/keithamus/rollup-plugin-brotli/compare/v2.0.1...v2.0.2
